### PR TITLE
Form api

### PR DESCRIPTION
**Pull request by Bogdan26Bogdan**
The method for creating the order and file objects and uploading to mongodb. 

Currently acting as a form page to allow you to view that it works. Can change to an api once we have decided on the format.

### CODE REVIEW

**Comment by Bogdan26Bogdan** [comment]
.env file will also need to be moved to the flask server folder.

**Comment by Bogdan26Bogdan** [comment]
Checkout pull request #7  first as that makes testing this one easier and builds off of this one.

**Comment by KyleTheMaker** [comment]
Great work putting this together! looking forward to confirming API details soon!

**Review by KyleTheMaker — COMMENTED** [review]
looks great!

**Review by KyleTheMaker — APPROVED** [review]
Be good and carry on!

**Pull request merged**
